name: "🐞 Bug report"
description: "Report a bug or unexpected behavior"
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please help us fix the issue by providing as much detail as possible.
  - type: input
    id: bug-summary
    attributes:
      label: "Bug summary"
      description: "Briefly describe the bug."
      placeholder: "A short summary of the bug."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce the bug?"
      placeholder: "1. Go to ...\n2. Click ...\n3. See error ..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe what you expected."
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually happened."
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please provide information about your environment (WordPress version, plugin version, browser, etc.)."
      placeholder: "WordPress 6.0, Plugin 1.2.3, Chrome 117, ..."
    validations:
      required: false
