name: "❓ Question"
description: "Ask a question about the plugin, usage, or integration."
title: "[Question]: "
labels: [question]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please describe your question as clearly as possible. If it relates to a specific feature, usage, or integration, provide details.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you want to know or clarify?
      placeholder: "Describe your question here."
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of umami-wp-connect are you using?
      placeholder: "e.g. v0.1.1"
    validations:
      required: false
  - type: input
    id: wordpress-version
    attributes:
      label: WordPress Version
      description: Which version of WordPress are you using?
      placeholder: "e.g. 6.5.2"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots that might help answer your question.
      placeholder: "Optional: Add more details here."
    validations:
      required: false
