name: Block non-dev PRs to main

on:
  pull_request:
    branches:
      - main

jobs:
  block-non-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.head_ref != 'dev'
        run: |
          echo "Only PRs from dev to main are allowed."
          exit 1
